#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────
# Extracts the Ed25519 public key from .local/signing.key
# and writes demo-config.generated.ts with the key bytes.
# ──────────────────────────────────────────────────────────
set -euo pipefail

DEMO_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$DEMO_DIR/../../.." && pwd)"
KEY_FILE="$REPO_ROOT/.local/signing.key"
OUTPUT="$DEMO_DIR/src/demo-config.generated.ts"

if [ ! -f "$KEY_FILE" ]; then
  echo "ERROR: Signing key not found at $KEY_FILE"
  echo "Run 'bash backend/scripts/smoke-run.sh' from the repo root first."
  exit 1
fi

# Ed25519 private key is 64 bytes: 32-byte seed + 32-byte public key
# Extract the last 32 bytes (public key)
PUBLIC_KEY_HEX=$(tail -c 32 "$KEY_FILE" | xxd -p -c 32)

if [ ${#PUBLIC_KEY_HEX} -ne 64 ]; then
  echo "ERROR: Expected 32-byte public key (64 hex chars), got ${#PUBLIC_KEY_HEX}"
  exit 1
fi

# Convert hex to TypeScript Uint8Array literal: 0xAA, 0xBB, ...
TS_BYTES=""
for ((i = 0; i < ${#PUBLIC_KEY_HEX}; i += 2)); do
  BYTE="${PUBLIC_KEY_HEX:$i:2}"
  if [ -n "$TS_BYTES" ]; then
    TS_BYTES+=", "
  fi
  TS_BYTES+="0x${BYTE}"
done

cat > "$OUTPUT" << EOF
// Auto-generated by generate-config.sh — DO NOT EDIT
// Public key extracted from .local/signing.key

import { DEMO_KEY_ID } from './demo-config'

export const PUBLIC_KEYS: Readonly<Record<string, Uint8Array>> = {
  [DEMO_KEY_ID]: new Uint8Array([${TS_BYTES}]),
}
EOF

echo "Generated $OUTPUT"
echo "  Public key: ${PUBLIC_KEY_HEX}"
